[book]
authors = ["Lukas Wirth"]
language = "en"
multilingual = false
src = "src"
title = "The Little Book of Rust Macros"
edition = "2018"

[build]
create-missing = true
build-dir = "book"

[output.linkcheck]
traverse-parent-directories = false
optional = true

[output.html]
default-theme = "ayu"
site-url = "/tlborm/"
mathjax-support = true
git-repository-url = "https://github.com/veykril/tlborm/"
additional-css = ["res/rust-syntax-bg-highlight.css"]
